apiVersion: v1
kind: Secret
metadata:
 name: registrypullsecret
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJwaTMtMTo1MDAwIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NmNHRnpjM2R2Y21ReCIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
