services:

  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -Ubravo -d bravo_news" ]
      interval: 5s
      timeout: 1s
      retries: 100
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bravo
      - POSTGRES_PASSWORD=bravo
      - POSTGRES_DB=bravo_news
    networks:
      - btstnnet
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"

  api-proxy:
    image: lt:5000/api-proxy:dev
    restart: always
    depends_on:
      news-grabber-db-api:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=bravo
      - DATABASE_PASSWORD=bravo
    ports:
      - 8081:8080
    # mem_limit: 128m
    networks:
      - btstnnet

  news-grabber-db-api:
    image: lt:5000/news-grabber:dev
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8080
      - DATABASE_HOST=db
      - DATABASE_USERNAME=bravo
      - DATABASE_PASSWORD=bravo
      - DATABASE_NAME=bravo_news
    # mem_limit: 1024m
    networks:
      - btstnnet

  news-grabber-telegram-api:
    image: lt:5000/news-grabber-python:latest
    restart: always
    depends_on:
      news-grabber-db-api:
        condition: service_started
    environment:
      - TZ=Asia/Novosibirsk
      - API_ID=
      - API_HASH=
      - TELEGRAM_CHANNEL_NAMES=ON FLEEK investing - авторский канал об инвестициях;РынкиДеньгиВласть | РДВ;Сигналы РЦБ;IF Stocks;MarketTwits;Сигналы РЦБ US;Довольный капитал / DCP Investment;Z ИНВЕСТИЦИИ;IF News;Stock News;Financial Headlines;headlines;InvestFuture;Управляющий №1;Ритейлер Свифт;InVesti;Южный Капитал. Рынок США;ВТБ Мои Инвестиции;ИнвестОратор;ZORKO for RDV;Усиленные Инвестиции
      - TELEGRAM_GRABBER_DATABASE_URL=http://news-grabber-db-api:8080/news
      - MESSAGE_PER_CHANNEL_NUMBER=5000
    # mem_limit: 256m
    networks:
      - btstnnet

  frontend:
    image: btstn/frontend:dev
    restart: always
    depends_on:
      - api-proxy
    ports:
      - 8090:80
    environment:
      - USE_ANTIBOT=cookie
      - REACT_APP_ENV=prod
    mem_limit: 32m
    networks:
      - btstnnet

networks:
  btstnnet:
