version: '2.4'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bravo_news
    mem_limit: 128m
    networks:
      - bravonet

  api-proxy:
    image: btstn/api-proxy:dev
    restart: always
    depends_on:
      - news-grabber
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8081:8080
    mem_limit: 128m
    networks:
      - bravonet

  news-grabber:
    image: btstn/news-grabber:dev
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - TELEGRAM_APIID=
      - TELEGRAM_APIHASH=
      - TELEGRAM_PHONENUMBER=1234
#      - TELEGRAM_AUTHKEYPATH=
#      - TELEGRAM_DATACENTERPATH=
      - APP_SOURCES=ON FLEEK investing;РынкиДеньгиВласть | РДВ;Сигналы РЦБ;IF Stocks;MarketTwits
      - APP_STRATEGY=ALL
    mem_limit: 256m
    networks:
      - bravonet

  frontend:
    image: btstn/frontend:dev
    restart: always
    depends_on:
      - api-proxy
    ports:
      - 80:80
    environment:
      - USE_ANTIBOT=cookie
      - REACT_APP_ENV=prod
    mem_limit: 256m
    networks:
      - bravonet

networks:
  bravonet:
