version: "3.8"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bravo_news
    networks:
      - bravonet

  api-proxy:
    image: btstn/api-proxy:dev
    restart: always
    depends_on:
      - news-grabber
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8081:8080
    networks:
      - bravonet

  news-grabber:
    image: btstn/news-grabber:dev
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - TELEGRAM_APIID=
      - TELEGRAM_APIHASH=
      - TELEGRAM_PHONENUMBER=1234
      - TELEGRAM_AUTHKEYPATH=
      - TELEGRAM_DATACENTERPATH=
      - APP_SOURCES=ON FLEEK investing;РынкиДеньгиВласть | РДВ;Сигналы РЦБ;IF Stocks;MarketTwits
      - APP_STRATEGY=ALL
    networks:
      - bravonet

  frontend:
    image: btstn/frontend:dev
    restart: always
    depends_on:
      - api-proxy
    ports:
      - 8080:8080
    environment:
      - USE_ANTIBOT=cookie
      - REACT_APP_ENV=prod
    networks:
      - bravonet

networks:
  bravonet:
