version: "3.8"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bravo_news
    networks:
      - bravonet

  api-proxy:
    image: btstn/api-proxy:dev
    restart: always
    depends_on:
      - news-grabber
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
    - 8080:8080
    networks:
      - bravonet

  news-grabber:
    image: btstn/news-grabber:dev
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - TELEGRAM_APIID=
      - TELEGRAM_APIHASH=
      - TELEGRAM_PHONENUMBER=1234
      - APP_SOURCES=ON FLEEK investing;Сам ты инвестор!;Тинькофф Инвестиции;РынкиДеньгиВласть | РДВ;Сигналы РЦБ;IF Stocks;InvestFuture;RDV PREMIUM;ДОХОДЪ;ВТБ Мои Инвестиции;Довольный капитал / DCP Investment
    networks:
      - bravonet

networks:
  bravonet:
