apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: btstn
  name: news-grabber
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: btstn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: btstn
    spec:
      containers:
      - image: pi3-1:5000/news-grabber:dev
        name: news-grabber

