version: '3'

services:
  influxdb:
    image: influxdb:1.7.10-alpine
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: bravo
      DOCKER_INFLUXDB_INIT_PASSWORD: bravo
      DOCKER_INFLUXDB_INIT_ORG: bravo
      DOCKER_INFLUXDB_INIT_BUCKET: bravo
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
    networks:
      - telegraf_network

  telegraf:
    image: telegraf:1.15-alpine
    restart: always
    environment:
      USER: bravo
      INFLUX_URL: influxdb
      INFLUX_USER: bravo
      INFLUX_PASSWORD: bravo
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    networks:
      - telegraf_network

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - telegraf_network

networks:
  telegraf_network:
